spring.application.name=rag
spring.docker.compose.enabled=false
spring.datasource.url=${RAG_DATABASE_URL:jdbc:postgresql://localhost:5432/rag}
spring.datasource.username=${RAG_DATABASE_USERNAME:rag}
spring.datasource.password=${RAG_DATABASE_PASSWORD:rag}
server.error.include-message=never
server.error.include-stacktrace=never
